SLAM_node:
  AUV_mass: 33.5          # Set the AUV mass value here
  AUV_added_mass: 3.35     # Set the AUV added mass value here
  I_matrix:                # Set the inertial matrix values here
    - [36.85, 0.0  , 0.0  ,  0.0]
    - [0.0  , 36.85, 0.0  ,  0.0]
    - [0.0  , 0.0  , 36.85,  0.0]
    - [0.0  , 0.0  , 0.0  ,  1.0]
  Tau_g:  # Set the gravitational torque vector here
    - [0.0] 
    - [0.0] 
    - [9.81]
    - [0.0]
  Tau_b:  # Set the buoyancy torque vector here
    - [0.0] 
    - [0.0] 
    - [-9.81]
    - [0.0]
  Drag_co:                 # Set the drag coefficient values here
    - [5, 0.0, 0.0, 0.0]
    - [0.0, 5, 0.0, 0.0]
    - [0.0, 0.0, 5, 0.0]
    - [0.0, 0.0, 0.0, 5]
  Lift_co:                 # Set the lift coefficient values here
    - [1, 0.0, 0.0, 0.0]
    - [0.0, 1, 0.0, 0.0]
    - [0.0, 0.0, 1, 0.0]
    - [0.0, 0.0, 0.0, 1]
  R:                       # Set the motion model noise matrix here
    - [0.001, 0.0  , 0.0  , 0.0  , 0.0  , 0.0  , 0.0  , 0.0  ]
    - [0.0  , 0.001, 0.0  , 0.0  , 0.0  , 0.0  , 0.0  , 0.0  ]
    - [0.0  , 0.0  , 0.001, 0.0  , 0.0  , 0.0  , 0.0  , 0.0  ]
    - [0.0  , 0.0  , 0.0  , 0.001, 0.0  , 0.0  , 0.0  , 0.0  ]
    - [0.0  , 0.0  , 0.0  , 0.0  , 0.001, 0.0  , 0.0  , 0.0  ]
    - [0.0  , 0.0  , 0.0  , 0.0  , 0.0  , 0.001, 0.0  , 0.0  ]
    - [0.0  , 0.0  , 0.0  , 0.0  , 0.0  , 0.0  , 0.001, 0.0  ]
    - [0.0  , 0.0  , 0.0  , 0.0  , 0.0  , 0.0  , 0.0  , 0.001]
  C:                       # Set the output matrix "C" here
    - [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    - [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    - [0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    - [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0]
    - [0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0]
    - [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0]
    - [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]
    - [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0]
  ORB_sigma: 0.1           # Set the ORB variance value here
